quiz/quiz/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from quiz_app import views
# from account_app.regbackend import MyRegistrationView

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^quiz_app/', include('quiz_app.urls', namespace='quiz_app')),
]

quiz/quiz_app/urls.py
from django.conf.urls import url
from quiz_app import views

app_name = "quiz_app"

urlpatterns = [    
    url(r'^$', views.TopicListView.as_view(), name="quiz_list"),
    url(r'^(?P<pk>\d+)/$', views.TopicDetailView.as_view(), name="quiz_detail"),
]

quiz/account_app/models.py
from django.db import models

# Create your models here.

quiz/quiz_app/models.py
from django.db import models

# Create your models here.
class Topic(models.Model):
    topic_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    objects = models.Manager()

    def __str__(self):
        return str(self.topic_text)


class Question(models.Model):
    quiz_topic = models.ForeignKey(Topic, related_name="questions", on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)

    objects = models.Manager()

    def __str__(self):
        return str(self.question_text)

class Choice(models.Model):
    question = models.ForeignKey(Question, related_name="choices", on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    objects = models.Manager()

    def __str__(self):
        return str(self.choice_text)

quiz/account_app/forms.py
from django import forms

quiz/account_app/views.py
from django.shortcuts import render

# Create your views here.

quiz/quiz_app/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Topic, Question, Choice

# Create your views here.
def index(request):
    return render(request, 'index.html')

class TopicListView(LoginRequiredMixin, ListView):
    context_object_name = "topics"
    model = Topic
    

class TopicDetailView(LoginRequiredMixin, DetailView):
    context_object_name = "topic"
    model = Topic

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

quiz/quiz_app/templates/quiz_app/topic_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>{{topic}}</h2>
    {% for question in topic.questions.all %}
    <ul>
        <li>
        {{question.question_text}}        
        {% for choice in question.choices.all %}
        <ul>
            <li>
            {{choice}}
            </li>
        </ul>
        {% endfor %}
        </li>
    </ul>    
    {% endfor %}
{% endblock %}

quiz/quiz_app/templates/quiz_app/topic_list.html
{% extends "base.html" %}

{% block content %}
{% for topic in topics %}
    <ul>
        <li>
        <a href={% url 'quiz_app:quiz_detail' pk=topic.pk %}>{{topic}}</a>
        </li>
    </ul>
{% endfor %} 
{% endblock %}

quiz/templates/base.html
{% load i18n %}
<!doctype html>
<html lang="en">

<head>
    <title>Django Registration Test App</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
    <div class="container-fluid p-3">
    <div id="header">
    {% block header %}
    <a href="{% url 'index' %}">{% trans "Home" %}</a> |

    {% if user.is_authenticated %}
        {% trans "Logged in" %}: {{ user.get_username }}
        (<a href="{% url 'auth_logout' %}">{% trans "Log out" %}</a> |
        <a href="{% url 'auth_password_change' %}">{% trans "Change password" %}</a>)
        <a class="btn btn-primary float-right" href="{% url 'quiz_app:quiz_list' %}">Quiz List</a>
    {% else %}
       <a href="{% url 'auth_login' %}">{% trans "Log In" %}</a>
    {% endif %}
    {% endblock %}
    </div>

    <div id="content">
    <h1>{% block title %}{% endblock %}</h1>
    {% block content %}

    {% endblock content %}
    </div>

    <div id="footer">
    {% block footer %}

    {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</div>
</body>

</html>

quiz/templates/index.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Welcome to Quiz App{% endblock %}

{% block content %}
{% endblock %}

quiz/templates/profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Account Profile{% endblock %}

{% block content %}
{% endblock %}